const express =require('express')
const reportsRouter =require('./routers/reports')
require('./db/mongoose')
const app =express()
app.use(express.json())
app.use(reportsRouter)
const newsRouter =require('./routers/news')
app.use(newsRouter)
const port=3000
app.listen(port,()=>{console.log('server is running')})